title: Mortalman
description: This is a personal page that hosts my ideas,products,resources and everything about me.
# remote_theme: "jekyll/minima@1e8a445"
# minima:
#   skin: dark
#   nav_pages:
#     - tools/check.html
#     - about.md
